language: node_js
node_js:
- 6.3.0
before_script:
- npm install
script:
- npm test
- npm run coverage
env:
  global:
  - secure: l1pBXEG+tpI7Z/scuIbb4aeArzM0FBQmAmcRIrFpnv5k6SrToXiZZgKymejclGUAmGmbIejyM0qB2YU0SRx3uLCShaWFuG7YDIZb37tEZ15qu9XskGgh4XzI/ZgE7GEgivbfjAiYy2uFiBfq738DPdJLlF8FyrlF6TgoXUn+YEXJTUJ++k7OohCMCWzdI7LexbK5/ROj+qeHNNBdEeMSa7LOeB3y043SnySE+2T3bgjEPrEXRAtElNPfE89cOoQqlb3Iw2P0zVBCs86l8NjP6EQInm4HkYM5RHH5+W8/aLFmkqi0K/5tbUU8DdlRcqVvS5cFmB0HtD7X6SZiVKODzonxWXKv6DSkvUyAKUVeAJOujOI5ErCMJfjQgrd7DjG5qDY5qxcFFN9G+O45Otoxb9Y7T9dqmPxDRkdvvyZaKkXL5nU+SEiQSFoOc5bktn1vhbHLDQhDv9fK/N37b3n9AEas496ocERG4OilnD2Q5Ps8lLTKDpQYKvCKzRDdz+ZEDtjCtmeTea45nftcExNON12nT1+5mJHNX1qozhNf4Mylv9sxY2wnxIsNL0G7EBUqaPKqEcYQh1npc83HO302yqfkpOdWYlMy19ijDWpN4y+V7ipZX+IkZc2g6EtlQnz6KXG46CVhoFex6A3SsgwwMjb59mJf2OAeDa/0NTnSMp4=
  - secure: svAWEbwpoFjnXaeR9S3u8L2UM+liK51pahlO5S+JQFGrq4uiT8a+3Y8SGEXYypiVAjCLuFQXQEirGzqckWURPWW76C1cs2NVdTYrJHC31IS8k8bcP5lZmhWXBheBz5BPcNdo2Up78pP9e5I4h27A5KtR2RaWnwiCTKAhHLQba010bwX83/059XLnJIt/YjYmLBKlKblF3zLWfFlXyfSD5D1Uxk5JjtMvEHpG7WuWXKLHm52wD+xpHJtsEVvyBBG/WauHJJT4nHSSlF1NVEL8wQMrpo0iw4qQnWbMhcgZ7x8JPmfY2tuKWh8+/heq2WDsMw3/eLTJw27qrFlCZL8wvouyvtQbDDtt7M+LoEA5dqE3ltP9eUvT1faDbmX+KkAPJ23IkjDdudYgedyY4xUa03j7r69dwuIC4bOsBqkLlgAv4ev3FyK8TM8cxdqOCJymeLkG+VItqu2zWvWMB68e326Nz2UhsC7cU2ZHYsPBKsok4Sy/jv1VtxJVTAJJaJ3RAYOUDldA56l8+oemPlNz0G9QPVUjC58onwVmyKHnSFQXaljUJk+8MTNU3XSmlo/sDuUHe5ifwpwuOE6OflAFM6vwhVtXGJLDTXyu6PKBNwZnYyF2ZLimfLB4M2PU8dSI1t/5MG1c57ArQEefUm6GYqpOyq4NKcxVASvBA0liV5c=
